version: "3.8"

services:
  manager:
    image: stuxgames/gameservermanager:main
    restart: always

  list:
    image: stuxgames/gameserverlist:main
    restart: always

  proxy:
    restart: always

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --cleanup --interval 60 manager list proxy watchtower
    depends_on:
      - manager
      - list
      - proxy
